### Numpy 


> numpy -- numerical python..

> numpy is a multi-dimensional aray..

> its a python library.

> it is a fatser as compared to python list..

> Here we are gone have bunch of mathematically function for array operations..

> We can Intergrate numpy with other libraries like pandas, matplotlib, scikit-learn...

### Installing Numpy

In [1]:
! pip install numpy

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.6 MB 4.8 MB/s eta 0:00:03
   -------- ------------------------------- 2.6/12.6 MB 5.6 MB/s eta 0:00:02
   ------------- -------------------------- 4.2/12.6 MB 6.1 MB/s eta 0:00:02
   -------------------- ------------------- 6.3/12.6 MB 7.4 MB/s eta 0:00:01
   --------------------------- ------------ 8.7/12.6 MB 8.0 MB/s eta 0:00:01
   -------------------------------- ------- 10.2/12.6 MB 8.1 MB/s eta 0:00:01
   ---------------------------------------- 12.6/12.6 MB 8.5 MB/s eta 0:00:00



[notice] A new release of pip is available: 25.0.1 -> 26.2.1
[notice] To update, run: C:\Users\klegd\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [2]:
import numpy as np


In [6]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [7]:
narray=np.array([1, 2, 3, 4, 5])

In [8]:
type(narray)


numpy.ndarray

In [9]:
narray

array([1, 2, 3, 4, 5])

In [4]:
import numpy as np

l2 = [[1,2],[4,5]]
array2d = np.array(l2)

In [5]:
array2d

array([[1, 2],
       [4, 5]])

In [6]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
import numpy as np

In [9]:
array1=np.array([3,4,5,6])

In [10]:
type(array1)


numpy.ndarray

In [12]:
# shape
array1.shape

(4,)

### Array Operations

In [14]:
n1= np.array([3,5,2,1])
n2= np.array([2,5,6,7])

In [15]:
n1+n2


array([ 5, 10,  8,  8])

In [16]:
n1*n2

array([ 6, 25, 12,  7])

In [17]:
np.sqrt(n1)

array([1.73205081, 2.23606798, 1.41421356, 1.        ])

### Indexing and Slicing (Acessing elkements of array)

In [18]:
## 1d array (nd array)
a1= np.array([1,2,3,4,5,6,7,8,9,10])

print(a1[3])
#slicing
print(a1[2:5])

4
[3 4 5]


In [19]:
### Boolean indexing
a1[a1>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [20]:
for i in range(1,11):
    print(i)

1
2
3
4
5
6
7
8
9
10


### Reshapng of array

In [21]:
rarray =np.arange(10)
rarray


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
len(rarray)

10

In [24]:
reshape = rarray.reshape((2, 5))
print(reshape)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [26]:
reshape[1][3]

np.int64(8)

### Matrix Multiplication

In [30]:
m1= np.ones((3,2))
m2 = np.array([[3,4,5],[6,7,8]])
print(m1)
print(m2)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[3 4 5]
 [6 7 8]]
